language: csharp
solution: ./CCBQuickCategorizer.sln
mono: none
dotnet: 6.0.302
script:
- chmod +x ./deploy.sh 
- ./deploy.sh

# safelist
branches:
  only:
  - master
  - release
  - develop