language: csharp
project: ./src/CCBQuickCategorizerV2.csproj
mono: none
dotnet: 5.0
script:
- chmod +x ./deploy.sh 
- ./deploy.sh

# safelist
branches:
  only:
  - master
  - release
  - develop
