language: csharp
solution: ./CCBQuickCategorizer.sln
mono: none
dotnet: 6.0.302
script:
- chmod +x ./build_me.sh 
- ./build_me.sh

# safelist
branches:
  only:
  - master
  - release
  - develop